### ISSUE TITLE
Syntax error can cause dogma to crash

### ISSUE THREAD

**Issue by RobinClowers** [lpil/dogma#176]
We had a `exs` file with bad syntax, and dogma crashed on it, when running the QuotesInString rule. This happened after a merge, but also, this script doesn't always get parsed in our dev environment.

Output:

```bash
** (EXIT from #PID<0.47.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Dogma.Rule.QuotesInString.check_binary_strings/2
        lib/dogma/rule/quotes_in_string.ex:25: Dogma.Rule.QuotesInString.check_binary_strings(nil, [])
        (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
        (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1043: Enum.map/2
        lib/dogma/script.ex:97: Dogma.Script.run_tests/2
        lib/dogma/rules.ex:22: Dogma.Rules.test_script/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
[error] Task #PID<0.947.0> started from #PID<0.47.0> terminating
** (FunctionClauseError) no function clause matching in Dogma.Rule.QuotesInString.check_binary_strings/2
    lib/dogma/rule/quotes_in_string.ex:25: Dogma.Rule.QuotesInString.check_binary_strings(nil, [])
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    lib/dogma/script.ex:97: Dogma.Script.run_tests/2
    lib/dogma/rules.ex:22: Dogma.Rules.test_script/3
    (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<1.34862213/0 in Dogma.Rules.test/3>
    Args: []
```
We tracked it to `script.tokens` being nil in the `QuotesInString` rule: https://github.com/lpil/dogma/blob/master/lib/dogma/rule/quotes_in_string.ex#L19.

We inspected the value of `script` and dogma had found the syntax error, so maybe it would make sense to short circuit when there is a syntax error?

**Comment by lpil** [comment]
Hi, thanks for the report.

This is the intended behaviour, but I believe it does not currently work. There is an ticket open for it. Hopefully we'll get it fixed soon. :)
