### ISSUE TITLE
Dogma fails to parse special characters

### ISSUE THREAD

**Issue by jlee0831** [lpil/dogma#195]
Dogma fails with:

```
** (FunctionClauseError) no function clause matching in Dogma.Util.ScriptStrings.parse_string_literal/2
    lib/dogma/util/script_strings.ex:37: Dogma.Util.ScriptStrings.parse_string_literal(<<211, 34, 10, 32, 32, 101, 110, 100, 10, 101, 110, 100, 10>>, "defmodule Foo do\n  def foo do\n    \"")
    lib/dogma/script.ex:89: Dogma.Script.add_processed_source/1
    lib/dogma/script.ex:47: Dogma.Script.parse/2
    lib/dogma/script_sources.ex:42: anonymous fn/2 in Dogma.ScriptSources.to_scripts/1
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/dogma/script_sources.ex:39: Dogma.ScriptSources.to_scripts/1
    lib/dogma.ex:17: Dogma.run/3
    lib/mix/tasks/dogma.ex:23: Mix.Tasks.Dogma.run/1
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

when trying to parse 
```
defmodule Foo do
  def foo do
    "Ó"
  end
end
```

**Comment by lpil** [comment]
Thanks!

**Comment by smeevil** [comment]
Fixed in https://github.com/lpil/dogma/pull/197

**Comment by lpil** [comment]
Thank you @smeevil !
