### ISSUE TITLE
Crash for unknown reasons.

### ISSUE THREAD

**Issue by fazibear** [lpil/dogma#202]
```
mix dogma /Users/fazibear/dev/sprint-poker/

nofile:34: warning: you are piping into a function call without parentheses, which may be ambiguous. Please wrap the function you are piping into in parentheses. For example:

    foo 1 |> bar 2 |> baz 3

Should be written as:

    foo(1) |> bar(2) |> baz(3)

Inspecting 637 files.

** (EXIT from #PID<0.47.0>) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.hd(nil)
        lib/dogma/rule/function_arity.ex:46: Dogma.Rule.FunctionArity.get_fun_details/1
        lib/dogma/rule/function_arity.ex:29: Dogma.Rule.FunctionArity.check_node/3
        (elixir) lib/macro.ex:188: anonymous fn/4 in Macro.do_traverse/4
        (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:187: Macro.do_traverse/4
        (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3

17:18:48.493 [error] Task #PID<0.576.0> started from #PID<0.47.0> terminating
** (ArgumentError) argument error
    :erlang.hd(nil)
    lib/dogma/rule/function_arity.ex:46: Dogma.Rule.FunctionArity.get_fun_details/1
    lib/dogma/rule/function_arity.ex:29: Dogma.Rule.FunctionArity.check_node/3
    (elixir) lib/macro.ex:188: anonymous fn/4 in Macro.do_traverse/4
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:187: Macro.do_traverse/4
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
Function: #Function<1.53947851/0 in Dogma.Rules.test/3>
    Args: []
```

**Comment by lpil** [comment]
Can you share a small example of code in which this crash occurs?

**Comment by fazibear** [comment]
I think its not about code. Ex
There are 2 projects `sprint-poker` in `~/dev/sprint-poker` and `dash` in `~/dev/dash` both have dogma installed in `mix.exs`
When i run `mix dogma` in `sprint-poker` dir or in `dash` dir everything works well.
But when I run `mix dogma ~/dev/dash` from `~/dev/sprint-poker` dir it will crash. Same crash when I run `mix dogma ~/dev/sprint-poker` from `~/dev/dash` dir.

**Comment by lpil** [comment]
Heya! I've just done some testing and running Dogma outside the target directory works as expected, so there is another problem. Could you perhaps provide a small code example that reproduces this problem please?

I'll close this until then.

**Comment by fazibear** [comment]
Sure. Clone `https://github.com/elpassion/sprint-poker` repo. Add `dogma` to mix.exs. `mix dogma` work fine. But `mix dogma /Users/fazibear/dev/sprint-poker` fails
```
~/dev/sprint-poker ➜ mix dogma /Users/fazibear/dev/sprint-poker
nofile:34: warning: you are piping into a function call without parentheses, which may be ambiguous. Please wrap the function you are piping into in parentheses. For example:

    foo 1 |> bar 2 |> baz 3

Should be written as:

    foo(1) |> bar(2) |> baz(3)

Inspecting 637 files.

** (EXIT from #PID<0.47.0>) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.hd(nil)
        lib/dogma/rule/function_arity.ex:46: Dogma.Rule.FunctionArity.get_fun_details/1
        lib/dogma/rule/function_arity.ex:29: Dogma.Rule.FunctionArity.check_node/3
        (elixir) lib/macro.ex:188: anonymous fn/4 in Macro.do_traverse/4
        (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:187: Macro.do_traverse/4
        (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3

22:23:41.845 [error] Task #PID<0.562.0> started from #PID<0.47.0> terminating
** (ArgumentError) argument error
    :erlang.hd(nil)
    lib/dogma/rule/function_arity.ex:46: Dogma.Rule.FunctionArity.get_fun_details/1
    lib/dogma/rule/function_arity.ex:29: Dogma.Rule.FunctionArity.check_node/3
    (elixir) lib/macro.ex:188: anonymous fn/4 in Macro.do_traverse/4
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:187: Macro.do_traverse/4
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
Function: #Function<1.53947851/0 in Dogma.Rules.test/3>
    Args: []
```

**Comment by lpil** [comment]
Thank you.

**Comment by ThijsWouters** [comment]
I also had this crash.

I managed to track the error down to Phoenix. On [this](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/template.ex#L367) line, there is a variable defined called `defp`. This generates a node like `{:defp, [line: 367], nil}`. The last nil generates the crash.
