### ISSUE TITLE
Syntax error results in crash

### ISSUE THREAD

**Issue by toupeira** [lpil/dogma#205]
Example code:

```elixir
def foo) do
end
```

Error message:
```
** (EXIT from #PID<0.47.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:116: Enumerable.reduce/3
        (elixir) lib/enum.ex:1486: Enum.reduce/3
        (elixir) lib/enum.ex:742: Enum.filter/2
        lib/dogma/rule/hard_tabs.ex:18: Dogma.Rule.HardTabs.test/2
        (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
        lib/dogma/runner.ex:11: Dogma.Runner.run_tests/2
```

**Comment by lpil** [comment]
I'll release a new version now.

**Comment by toupeira** [comment]
Well, that was quick :grinning: Thanks!

**Comment by lpil** [comment]
:)

**Comment by toupeira** [comment]
With a module it seems the message gets lost somehow:

```elixir
defmodule Foo do
  def foo) do
  end
end
```

```sh
$ mix dogma foo.exs
Inspecting 1 file.

X
$ mix dogma --format=flycheck foo.exs
$ echo $?
154
$ elixir foo.exs
** (SyntaxError) foo.exs:4: unexpected token: ")". "do" starting at line 3 is missing terminator "end"
    (elixir) lib/code.ex:363: Code.require_file/2
```

Also I saw that `Dogma.Reporter.FlyCheck#format_error` hard-codes the errors as warnings, can this be changed so syntax errors output `E`? In return I'll submit a PR for basic syntastic.vim integration :)

**Comment by lpil** [comment]
So it does, how interesting. We need to add a test that asserts syntax errors are formatted and printed correctly, and then this to be implemented. Please do open a ticket :)
