### ISSUE TITLE
Dogma.Rule.TakenName does not handle def unquote(name)(...)

### ISSUE THREAD

**Issue by KronicDeth** [lpil/dogma#208]
## Error

```
(Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 266], [{:quoted_name, [line: 266], nil}]}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    lib/dogma/rule/taken_name.ex:72: Dogma.Rule.TakenName.check_name/4
    (elixir) lib/macro.ex:199: Macro.do_traverse/4
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:205: Macro.do_traverse/4
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:187: Macro.do_traverse/4
Function: #Function<1.54447878/0 in Dogma.Rules.test/3>
    Args: []
```

## Code

```elixir
  defp quoted_action(quoted_name) do
    quote do
      def unquote(quoted_name)(conn, params) do
        MyApp.Controller.Rpc.unquote(quoted_name)(conn, params, __configuration__)
      end
    end
  end
```

Line 266 is `def unquote(quoted_name)(conn, params) do`

**Comment by lpil** [comment]
Thanks :)
