### ISSUE TITLE
Erlang terms in module name makes dogma crash

### ISSUE THREAD

**Issue by AndrewDryga** [lpil/dogma#221]
Module
```
defmodule :ap_api_tasks do
  @moduledoc """
  Nice way to apply migrations inside a released application.
  ...
```

Run result
```
~/Projects/www/os.ap.api(master ✗) mix dogma
Inspecting 25 files.

** (EXIT from #PID<0.70.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: :ap_api_tasks
        lib/dogma/rule/module_doc.ex:44: Dogma.Rule.ModuleDoc.check_node/2
        (elixir) lib/macro.ex:257: Macro.traverse/4
        lib/dogma/script.ex:124: Dogma.Script.walk/2
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        lib/dogma/runner.ex:16: Dogma.Runner.run_tests/2
        lib/dogma/rules.ex:22: Dogma.Rules.test_script/3
        (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2

13:43:49.429 [error] Task #PID<0.182.0> started from #PID<0.70.0> terminating
** (MatchError) no match of right hand side value: :ap_api_tasks
    lib/dogma/rule/module_doc.ex:44: Dogma.Rule.ModuleDoc.check_node/2
    (elixir) lib/macro.ex:257: Macro.traverse/4
    lib/dogma/script.ex:124: Dogma.Script.walk/2
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    lib/dogma/runner.ex:16: Dogma.Runner.run_tests/2
    lib/dogma/rules.ex:22: Dogma.Rules.test_script/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
Function: #Function<1.53947851/0 in Dogma.Rules.test/3>
    Args: []
```

**Comment by lpil** [comment]
Looks like a new clauses needs to be added to `Dogma.Rule.ModuleDoc.check_node/2` to handle this case.
