### ISSUE TITLE
no function clause matching in Dogma.Rule.FunctionParentheses.check_function_parens/2

### ISSUE THREAD

**Issue by ChuckIrvine** [lpil/dogma#239]
Invoking dogma on the partial file:

```
defmodule KV.BucketTest do
  use ExUnit.Case, async: true
```

gives:

```
06:55:36.529 [error] Task #PID<0.90.0> started from #PID<0.70.0> terminating
** (FunctionClauseError) no function clause matching in Dogma.Rule.FunctionParentheses.check_function_parens/2
    lib/dogma/rule/function_parentheses.ex:37: Dogma.Rule.FunctionParentheses.check_function_parens(nil, [])
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    lib/dogma/script.ex:105: Dogma.Script.run_tests/2
    lib/dogma/rules.ex:22: Dogma.Rules.test_script/3
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<1.35272571/0 in Dogma.Rules.test/3>
    Args: []
```

**Comment by lpil** [comment]
That file is invalid syntax, right?

I thought we guarded against that. What version are you running?

**Comment by ChuckIrvine** [comment]
I’m using flycheck-dogma: 

https://github.com/aaronjensen/flycheck-dogma <https://github.com/aaronjensen/flycheck-dogma>

So, the file is being checked continually as I type in code.

I’m using the latest, e.g. 0.1.14

Thanks for looking into this.
