### ISSUE TITLE
protocol Enumerable not implemented for "'='"

### ISSUE THREAD

**Issue by houshuang** [lpil/dogma#55]
```elixir
Inspecting 257 files.

** (Protocol.UndefinedError) protocol Enumerable not implemented for "'='"
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:112: Enumerable.reduce/3
    (elixir) lib/enum.ex:1274: Enum.reduce/3
    (elixir) lib/enum.ex:1040: Enum.map_reduce/3
    (elixir) lib/macro.ex:175: Macro.do_prewalk/3
    (elixir) lib/macro.ex:188: Macro.do_prewalk/3
    lib/dogma/script.ex:54: Dogma.Script.walk/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
```

**Comment by lpil** [comment]
Can you offer more context please?

**Comment by houshuang** [comment]
This is the only message I got when trying to run dogma on my project... The project is at https://github.com/houshuang/survey.

**Comment by lpil** [comment]
Thanks.

What version of Dogma are you running?

**Comment by houshuang** [comment]
I tried again with HEAD, and it's the same thing. I put in an IO.inspect
just below the function definition of walk in lib/dogma/script.ex, here's
the output:

```elixir
[%Dogma.Script{ast: {:error, {1, "syntax error before: ", "'='"}}, errors:
[],
  lines: [{1, "defmodule <%= module %>Channel do"},
   {2, "  use <%= base %>.Web, :channel"}, {3, ""},
   {4, "  def join(\"<%= plural %>:lobby\", payload, socket) do"},
   {5, "    if authorized?(payload) do"}, {6, "      {:ok, socket}"},
   {7, "    else"}, {8, "      {:error, %{reason: \"unauthorized\"}}"},
   {9, "    end"}, {10, "  end"}, {11, ""},
   {12, "  # Channels can be used in a request/response fashion"},
   {13, "  # by sending replies to requests from the client"},
   {14, "  def handle_in(\"ping\", payload, socket) do"},
   {15, "    {:reply, {:ok, payload}, socket}"}, {16, "  end"}, {17, ""},
   {18, "  # It is also common to receive messages from the client and"},
   {19,
    "  # broadcast to everyone in the current topic (<%= plural
%>:lobby)."},
   {20, "  def handle_in(\"shout\", payload, socket) do"},
   {21, "    broadcast socket, \"shout\", payload"},
   {22, "    {:noreply, socket}"}, {23, "  end"}, {24, ""},
   {25, "  # This is invoked every time a notification is being broadcast"},
   {26, "  # to the client. The default implementation is just to push it"},
   {27, "  # downstream but one could filter or change the event."},
   {28, "  def handle_out(event, payload, socket) do"},
   {29, "    push socket, event, payload"}, {30, "    {:noreply, socket}"},
   {31, "  end"}, {32, ""},
   {33, "  # Add authorization logic here as required."},
   {34, "  defp authorized?(_payload) do"}, {35, "    true"}, {36, "  end"},
   {37, "end"}],
  path: "_build/dev/lib/phoenix/priv/templates/channel/channel.ex",
  source: "defmodule <%= module %>Channel do\n  use <%= base %>.Web,
:channel\n\n  def join(\"<%= plural %>:lobby\", payload, socket) do\n    if
authorized?(payload) do\n      {:ok, socket}\n    else\n      {:error,
%{reason: \"unauthorized\"}}\n    end\n  end\n\n  # Channels can be used in
a request/response fashion\n  # by sending replies to requests from the
client\n  def handle_in(\"ping\", payload, socket) do\n    {:reply, {:ok,
payload}, socket}\n  end\n\n  # It is also common to receive messages from
the client and\n  # broadcast to everyone in the current topic (<%= plural
%>:lobby).\n  def handle_in(\"shout\", payload, socket) do\n    broadcast
socket, \"shout\", payload\n    {:noreply, socket}\n  end\n\n  # This is
invoked every time a notification is being broadcast\n  # to the client.
The default implementation is just to push it\n  # downstream but one could
filter or change the event.\n  def handle_out(event, payload, socket) do\n
   push socket, event, payload\n    {:noreply, socket}\n  end\n\n  # Add
authorization logic here as required.\n  defp authorized?(_payload) do\n
 true\n  end\nend\n",
  valid?: false},
 #Function<0.61188148/2 in Dogma.Rules.DebuggerStatement.test/1>]
** (Protocol.UndefinedError) protocol Enumerable not implemented for "'='"
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:112: Enumerable.reduce/3
    (elixir) lib/enum.ex:1274: Enum.reduce/3
    (elixir) lib/enum.ex:1040: Enum.map_reduce/3
    (elixir) lib/macro.ex:175: Macro.do_prewalk/3
    (elixir) lib/macro.ex:188: Macro.do_prewalk/3
    lib/dogma/script.ex:55: Dogma.Script.walk/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
```

On Tue, Jul 14, 2015 at 10:49 PM, Louis Pilfold <notifications@github.com>
wrote:

> Thanks.
>
> What version of Dogma are you running?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lpil/dogma/issues/55#issuecomment-121263628>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by houshuang** [comment]
I tried again with HEAD, and it's the same thing. I put in an IO.inspect
just below the function definition of walk in lib/dogma/script.ex, here's
the output:

```elixir
[%Dogma.Script{ast: {:error, {1, "syntax error before: ", "'='"}}, errors:
[],
  lines: [{1, "defmodule <%= module %>Channel do"},
   {2, "  use <%= base %>.Web, :channel"}, {3, ""},
   {4, "  def join(\"<%= plural %>:lobby\", payload, socket) do"},
   {5, "    if authorized?(payload) do"}, {6, "      {:ok, socket}"},
   {7, "    else"}, {8, "      {:error, %{reason: \"unauthorized\"}}"},
   {9, "    end"}, {10, "  end"}, {11, ""},
   {12, "  # Channels can be used in a request/response fashion"},
   {13, "  # by sending replies to requests from the client"},
   {14, "  def handle_in(\"ping\", payload, socket) do"},
   {15, "    {:reply, {:ok, payload}, socket}"}, {16, "  end"}, {17, ""},
   {18, "  # It is also common to receive messages from the client and"},
   {19,
    "  # broadcast to everyone in the current topic (<%= plural
%>:lobby)."},
   {20, "  def handle_in(\"shout\", payload, socket) do"},
   {21, "    broadcast socket, \"shout\", payload"},
   {22, "    {:noreply, socket}"}, {23, "  end"}, {24, ""},
   {25, "  # This is invoked every time a notification is being broadcast"},
   {26, "  # to the client. The default implementation is just to push it"},
   {27, "  # downstream but one could filter or change the event."},
   {28, "  def handle_out(event, payload, socket) do"},
   {29, "    push socket, event, payload"}, {30, "    {:noreply, socket}"},
   {31, "  end"}, {32, ""},
   {33, "  # Add authorization logic here as required."},
   {34, "  defp authorized?(_payload) do"}, {35, "    true"}, {36, "  end"},
   {37, "end"}],
  path: "_build/dev/lib/phoenix/priv/templates/channel/channel.ex",
  source: "defmodule <%= module %>Channel do\n  use <%= base %>.Web,
:channel\n\n  def join(\"<%= plural %>:lobby\", payload, socket) do\n    if
authorized?(payload) do\n      {:ok, socket}\n    else\n      {:error,
%{reason: \"unauthorized\"}}\n    end\n  end\n\n  # Channels can be used in
a request/response fashion\n  # by sending replies to requests from the
client\n  def handle_in(\"ping\", payload, socket) do\n    {:reply, {:ok,
payload}, socket}\n  end\n\n  # It is also common to receive messages from
the client and\n  # broadcast to everyone in the current topic (<%= plural
%>:lobby).\n  def handle_in(\"shout\", payload, socket) do\n    broadcast
socket, \"shout\", payload\n    {:noreply, socket}\n  end\n\n  # This is
invoked every time a notification is being broadcast\n  # to the client.
The default implementation is just to push it\n  # downstream but one could
filter or change the event.\n  def handle_out(event, payload, socket) do\n
   push socket, event, payload\n    {:noreply, socket}\n  end\n\n  # Add
authorization logic here as required.\n  defp authorized?(_payload) do\n
 true\n  end\nend\n",
  valid?: false},
 #Function<0.61188148/2 in Dogma.Rules.DebuggerStatement.test/1>]
** (Protocol.UndefinedError) protocol Enumerable not implemented for "'='"
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:112: Enumerable.reduce/3
    (elixir) lib/enum.ex:1274: Enum.reduce/3
    (elixir) lib/enum.ex:1040: Enum.map_reduce/3
    (elixir) lib/macro.ex:175: Macro.do_prewalk/3
    (elixir) lib/macro.ex:188: Macro.do_prewalk/3
    lib/dogma/script.ex:55: Dogma.Script.walk/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
```

**Comment by lpil** [comment]
Ah, yes. This is because we're doing something stupid with errors. See #39 

Currently if you have a syntax error in a file Dogma isn't going to work. Will be simple to fix, but I've been away for a week and a bit.

In this case, Dogma thinks that `{1, "syntax error before: ", "'='"}` is the AST of a function call, and the last value in the tuple is supposed to be a list of arguments, which explodes when you try and iterate over it. Times like this I wish Elixir had types...

**Comment by lpil** [comment]
Could you try again on master please? :)
